### PR TITLE
Add the ability to specify PermitDynamic() and PermitDynamicIf() state trigger handlers.

### PR DESCRIPTION
**Pull request by keithballantyne**
Add the ability to specify PermitDynamic() and PermitDynamicIf() state trigger handlers which take Func's returning the next state. This would be similar to the StateLess PermitDynaimc trigger handlers.

eg
                .PermitDynamic(Trigger.Ring, new[] { State.Ringing, State.Connected }, 
                           async () => 
                           {
                                Console.WriteLine("Attempting to ring"); 
                                return true ? State.Ringing : State.Connected;
                            })

### CODE REVIEW

**Comment by prasannavl** [comment]
Wow. That's a large commit. Thanks! I've been contemplating on adding this feature myself, but didn't quite get the time to. 

This was also just being discussed here at #7 

I was exploring alternate ways of doing dynamic states. Let me do an analysis on which direction to take. In first glance, this looks like a pretty complete solution, if this directions seems best.

**Comment by prasannavl** [comment]
While this feature is undoubtedly one that is on the cards, the way it has been implemented rather seems hacky. I'm afraid merging this may not be the best idea. 

I really appreciate the effort. Unfortunately, I'm going to having to rethink the implementation. I'd rather not have a feature for the sake of it.

**Comment by keithballantyne** [comment]
I have several systems that are using Stateless with dynamic triggers. I
would like to use liquidState to allow better async support.

You definitely have a better understanding of what would be best, so please
proceed with a clean and performant solution.

Thanks,
Keith

**Comment by prasannavl** [comment]
PermitDynamic has now been finished.
Pull request over-ridden by commits: ebdf2aa through 3d8b06c

**Comment by prasannavl** [comment]
Pre-release available. Changes in the README on dev branch. Please let me know if this solves your issue. And I haven't tested it, So, it'll remain as pre-release for a while, and any tests from your side would be appreciated. :)

**Pull request closed without merging**
